export const pagesArr = {
  life: 1,
  goodsClassify: 2,
  flashPurchase: 3,
  specialSale: 4,
  specialArea: 5,
  goodsDetail: 6,
  search: 7,
  cart: 8,
  settlement: 9,
  couponList: 10,
  couponSelect: 11,
  orderList: 12,
  orderDetail: 13,
  specialDetail: 14,
  orderApply: 15,
  applyBarter: 16,
  barterDetail: 17,
  applyRefund: 18,
  refundDetail: 19,
  writeLogisticsl: 20,
  logisticsList: 21,
  logisticsSelf: 22,
  logisticsExpress: 23,
  logisticsBusiness: 24,
  addressList: 25,
  addressEdit: 26,
  addressMap: 27,
  home: 28,
  butler: 29,
  neighbours: 30,
  personage: 31,
  login: 32,
  applist: 33,
  agreement: 34,
  entranceIndex: 35,
  entranceList: 36,
  noticeIndex: 37,
  noticeDetails: 38,
  repairsIndex: 39,
  repairsDetails: 40,
  repairsList: 41,
  repairsEvaluate: 42,
  freeserverIndex: 43,
  freeserverList: 44,
  freeserverConfirm: 45,
  visitorIndex: 46,
  visitorInvite: 47,
  visitorVisitorList: 48,
  visitorInviteList: 49,
  visitorEdit: 50,
  compraiseIndex: 51,
  compraiseList: 52,
  compraiseDetails: 53,
  questionnaireIndex: 54,
  questionnaireDetails: 55,
  questionnaireMy: 56,
  propertyIndex: 57,
  convenienceIndex: 58,
  neighboursPublish: 59,
  neighboursDetails: 60,
  neighboursGroupList: 61,
  neighboursReply: 62,
  settingIndex: 63,
  settingAccount: 64,
  informationIndex: 65,
  houseAttestation: 66,
  houSelectCommunity: 67,
  houSeselectHouse: 68,
  informationPhone: 69,
  informationPaymentCode: 70,
  informationForgetPaymentCode: 71,
  informationLoginPassword: 72,
  feedbackIndex: 73,
  feedbackList: 74,
  feedbackDetails: 75,
  transactionIndex: 76,
  transactionDetails: 77,
  messageIndex: 78,
  happinessCoinIndex: 79,
  happinessCoinRecord: 80,
  happinessCoinBuyRecord: 81,
  happinessCoinDetails: 82,
  happinessCoinPayment: 83,
  interactionIndex: 84,
  questionIndex: 85,
  scanCodeIndex: 86,
  agreementList: 87,
  settingShield: 88,
  openingPage: 89,
  faceCollect: 90,
  settingAbout: 91,
  orderVerification: 92,
  livePayIndex: 93, // 生活缴费首页
  livePayPay: 94, // 生活缴费支付
  livePayRecord: 95, // 生活缴费记录
  livePayRecordDetail: 96, // 生活缴费记录详情
  livePayCostDetail: 97, // 生活缴费费用详情
  waterElectricitySelect: 98, // 水电费选择房间
  waterElectricityMeter: 99, // 水电抄表
  faceCollectCamera: 100, // 人脸收集拍照
  certification: 101, // 实名认证
  personInfo: 102, // 个人信息
  realNameInfo: 103, // 实名信息
  addBankCard: 104, // 添加银行卡
  supportBankCardList: 105, // 支持的银行卡列表
  verifyPhone: 106, // 验证预留手机号
  payAgreeMent: 107, // 支付协议
  bankCard: 108 // 我的银行卡
}
